[package]
name    = "api"
version = "0.1.0"
authors = ["Ty Cobb <ty.cobb.m@gmail.com>"]

[dependencies]
rocket = "0.4.0-rc.1"
dotenv = "0.10.1"

[dependencies.diesel]
version  = "1.3.3"
features = ["postgres"]
